import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body className="mt-5 mb-4">
        <nav style={{ padding: '1rem', borderBottom: '1px solid #ccc' }}>
          <Link className ="home" href="/home" style={{ marginRight: '1rem' }}>OrderDetails</Link>
          <Link  className ="home" href="/orderreceiptcard">OrderReceiptCard</Link>
          <Link  className ="home" href="/deliveryreceipt">DeliveryReceipt</Link>
        </nav>
        <main style={{ padding: '1rem' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
